# Generated by Django 4.2.7 on 2026-05-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
