# Generated by Django 4.2.7 on 2026-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_historicaltripstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deviation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='deviation_target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_deviated',
            field=models.BooleanField(default=False),
        ),
    ]
