# Generated by Django 4.2.7 on 2026-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_expense_deviation_reason_expense_deviation_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelclaim',
            name='deviation_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='has_deviations',
            field=models.BooleanField(default=False),
        ),
    ]
