# Generated by Django 4.2.7 on 2026-04-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_travelclaim_deviation_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='planned_destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='planned_origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='planned_destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='planned_origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
