# Generated by Django 4.2.7 on 2026-04-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_expense_planned_destination_expense_planned_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='row_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
