# Generated by Django 4.2.7 on 2026-04-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_expense_row_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveladvance',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='traveladvance',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Manager Approved', 'Manager Approved'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under Process', 'Under Process'), ('Transferred', 'Transferred'), ('Rejected by Finance', 'Rejected by Finance'), ('Paid', 'Paid'), ('PENDING_HR', 'Pending HR Approval'), ('PENDING_EXECUTIVE', 'Pending Finance Executive'), ('PENDING_HEAD', 'Pending Finance Head'), ('PENDING_FINAL_RELEASE', 'Pending Final Release'), ('REJECTED_BY_HEAD', 'Rejected by Finance Head'), ('COMPLETED', 'Completed'), ('PARTIALLY_COMPLETED', 'Partially Completed')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='travelclaim',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Manager Approved', 'Manager Approved'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under Process', 'Under Process'), ('Transferred', 'Transferred'), ('Rejected by Finance', 'Rejected by Finance'), ('Paid', 'Paid'), ('PENDING_HR', 'Pending HR Approval'), ('PENDING_EXECUTIVE', 'Pending Finance Executive'), ('PENDING_HEAD', 'Pending Finance Head'), ('PENDING_FINAL_RELEASE', 'Pending Final Release'), ('REJECTED_BY_HEAD', 'Rejected by Finance Head'), ('PARTIALLY_COMPLETED', 'Partially Completed')], default='Draft', max_length=50),
        ),
    ]
