# Generated by Django 4.2.7 on 2026-05-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_traveladvance_paid_amount_travelclaim_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkactivitybatch',
            name='executive_approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
