# Generated by Django 4.2.7 on 2026-05-02 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0008_bulkactivitybatch_executive_approved_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkactivitybatch',
            name='executive_approved_amount',
        ),
        migrations.CreateModel(
            name='FinanceWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence_order', models.PositiveIntegerField(unique=True)),
                ('can_edit_amount', models.BooleanField(default=False)),
                ('visibility_type', models.CharField(choices=[('INBOX', 'Inbox Only'), ('FINANCE_HUB', 'Finance Hub Only'), ('BOTH', 'Both Inbox and Finance Hub')], default='INBOX', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_workflow_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finance Workflow Step',
                'verbose_name_plural': 'Finance Workflow Steps',
                'ordering': ['sequence_order'],
            },
        ),
    ]
