# Generated by Django 4.2.7 on 2026-05-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_remove_bulkactivitybatch_executive_approved_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='executive_approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
