# Generated by Django 4.2.7 on 2026-05-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_trip_executive_approved_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='executive_approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
