# Generated by Django 4.2.7 on 2026-05-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_trip_finance_remarks_trip_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkactivitybatch',
            name='approver_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traveladvance',
            name='approver_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='approver_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='approver_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
