# Generated by Django 4.2.7 on 2026-05-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_bulkactivitybatch_approver_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkactivitybatch',
            name='requester_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='traveladvance',
            name='requester_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelclaim',
            name='requester_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='requester_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
