# Generated by Django 5.1.1 on 2026-05-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_financeworkflowstep_position_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrpositionconfig',
            name='can_approve',
            field=models.BooleanField(default=False),
        ),
    ]
