# Generated by Django 5.1.1 on 2026-05-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_hrpositionconfig_can_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrintimation',
            name='is_approval',
            field=models.BooleanField(default=False),
        ),
    ]
