# Generated by Django 5.1.1 on 2026-06-02 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_hrintimation_is_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financeworkflowstep',
            name='trip_control',
            field=models.CharField(choices=[('APPROVAL', 'Approval'), ('MARK_READ', 'Mark as Read')], default='APPROVAL', max_length=20),
        ),
        migrations.AddField(
            model_name='financeworkflowstep',
            name='trip_type',
            field=models.CharField(choices=[('BOTH', 'Both Trip & Travel'), ('TRIP', 'Trip Only (Local)'), ('TRAVEL', 'Travel Only (Outstation)')], default='BOTH', max_length=20),
        ),
        migrations.CreateModel(
            name='FinanceIntimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_position', models.CharField(blank=True, max_length=50)),
                ('is_approval', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finance_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_intimations', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_intimations', to='travel.trip')),
            ],
            options={
                'verbose_name': 'Finance Intimation',
                'verbose_name_plural': 'Finance Intimations',
            },
        ),
    ]
