# Generated by Django 5.1.1 on 2026-06-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_financeworkflowstep_trip_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeworkflowstep',
            name='trip_type',
            field=models.CharField(choices=[('BOTH', 'Both Trip & Travel'), ('TRIP', 'Trip Only (Local)'), ('TRAVEL', 'Travel Only (Outstation)'), ('NONE', 'None')], default='BOTH', max_length=20),
        ),
    ]
