# Generated by Django 5.1.1 on 2026-06-12 06:05
# FIXED: Runs actual ALTER TABLE on fresh databases (removed SeparateDatabaseAndState no-op).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_alter_financeworkflowstep_trip_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hrpositionconfig',
            options={'ordering': ['sequence_order'], 'verbose_name': 'HR Position Configuration', 'verbose_name_plural': 'HR Position Configurations'},
        ),
        migrations.AddField(
            model_name='hrpositionconfig',
            name='bulk_approval',
            field=models.CharField(choices=[('MARK_READ', 'Mark as Read'), ('APPROVAL', 'Formal Approval')], default='MARK_READ', max_length=20),
        ),
        migrations.AddField(
            model_name='hrpositionconfig',
            name='claims_approval',
            field=models.CharField(choices=[('MARK_READ', 'Mark as Read'), ('APPROVAL', 'Formal Approval')], default='MARK_READ', max_length=20),
        ),
        migrations.AddField(
            model_name='hrpositionconfig',
            name='edit_claims',
            field=models.CharField(choices=[('READ_ONLY', 'Read Only'), ('CAN_EDIT', 'Can Edit')], default='READ_ONLY', max_length=20),
        ),
        migrations.AddField(
            model_name='hrpositionconfig',
            name='project_code',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='hrpositionconfig',
            name='sequence_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hrpositionconfig',
            name='trips_approval',
            field=models.CharField(choices=[('MARK_READ', 'Mark as Read'), ('APPROVAL', 'Formal Approval')], default='MARK_READ', max_length=20),
        ),
        migrations.AlterField(
            model_name='hrpositionconfig',
            name='position_id',
            field=models.CharField(max_length=50),
        ),
    ]
