# Generated by Django 5.1.1 on 2026-06-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_alter_hrpositionconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='allowed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max reimbursable amount per cadre entitlement rule', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='city_type_resolved',
            field=models.CharField(blank=True, help_text='State HQ / Districts / Others — auto-resolved from destination cluster_category', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='hr_amount_source',
            field=models.CharField(blank=True, choices=[('claimed', 'Claimed Amount'), ('allowed', 'Allowed Amount'), ('manual', 'Manually Edited')], help_text='Which amount HR chose or whether they manually edited', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='hr_selected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final amount HR approved for this expense line', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='policy_note',
            field=models.CharField(blank=True, help_text='Auto-generated note about entitlement status for HR reference', max_length=255, null=True),
        ),
    ]
