# Generated by Django 5.1.1 on 2026-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_expense_entitlement_hr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='finance_amount_source',
            field=models.CharField(blank=True, choices=[('claimed', 'Claimed Amount'), ('allowed', 'Allowed Amount'), ('manual', 'Manually Edited')], help_text='Which amount Finance chose or whether they manually edited', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='finance_selected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final amount Finance approved for this expense line', max_digits=10, null=True),
        ),
    ]
