# Generated by Django 5.1.1 on 2026-06-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_expense_finance_amount_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentaltypemaster',
            name='expense_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='incidentaltypemaster',
            unique_together={('expense_type', 'category')},
        ),
    ]
