# Generated by Django 5.1.1 on 2026-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_alter_incidentaltypemaster_expense_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeworkflowstep',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrpositionconfig',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
    ]
