# Generated by Django 5.1.1 on 2026-07-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_financeworkflowstep_can_view_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='hr_selected_by_role',
            field=models.CharField(blank=True, help_text='Role/Position name of the user who recorded this decision', max_length=50, null=True),
        ),
    ]
