# Generated by Django 5.1.1 on 2026-07-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_expense_hr_selected_by_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRWorkflowSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(default='General', max_length=100, unique=True)),
                ('is_parallel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'HR Workflow Setting',
                'verbose_name_plural': 'HR Workflow Settings',
            },
        ),
    ]
