# Generated by Django 5.1.1 on 2026-07-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_hrworkflowsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrpositionconfig',
            name='hr_level_type',
            field=models.CharField(choices=[('assistant_manager', 'Assistant Manager'), ('manager', 'Manager')], default='assistant_manager', max_length=50),
        ),
        migrations.AddField(
            model_name='hrworkflowsetting',
            name='enable_two_level_flow',
            field=models.BooleanField(default=False),
        ),
    ]
