# Generated by Django 5.1.1 on 2026-07-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_hrpositionconfig_hr_level_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='COOProjectSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=100)),
                ('coo_position_id', models.CharField(max_length=100)),
                ('coo_position_name', models.CharField(max_length=200)),
                ('enable_coo_approval', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'COO Project Setting',
                'verbose_name_plural': 'COO Project Settings',
                'unique_together': {('project_code', 'coo_position_id')},
            },
        ),
    ]
