# Generated by Django 5.1.1 on 2026-07-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_cooprojectsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceWorkflowSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(default='General', max_length=100, unique=True)),
                ('is_parallel', models.BooleanField(default=False)),
                ('enable_two_level_flow', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Finance Workflow Setting',
                'verbose_name_plural': 'Finance Workflow Settings',
            },
        ),
        migrations.AddField(
            model_name='financeworkflowstep',
            name='finance_level_type',
            field=models.CharField(choices=[('assistant_manager', 'Assistant Manager'), ('manager', 'Manager')], default='assistant_manager', max_length=50),
        ),
        migrations.AddField(
            model_name='financeworkflowstep',
            name='project_code',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='financeworkflowstep',
            name='sequence_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
