# Generated by Django 5.1.1 on 2026-07-09 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_financeworkflowsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeintimation',
            name='advance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_intimations', to='travel.traveladvance'),
        ),
        migrations.AddField(
            model_name='financeintimation',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_intimations', to='travel.travelclaim'),
        ),
        migrations.AlterField(
            model_name='financeintimation',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_intimations', to='travel.trip'),
        ),
    ]
