# Generated by Django 5.1.1 on 2026-06-13 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eligibilityrule',
            options={'verbose_name': 'Eligibility Rule', 'verbose_name_plural': 'Eligibility Rules'},
        ),
        migrations.AlterUniqueTogether(
            name='eligibilityrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cadre',
            name='designation_keywords',
            field=models.JSONField(default=list, help_text="Designation keywords to auto-match employees. e.g. ['COO','National Head']"),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='accommodation_districts',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max per-night hotel cost when destination cluster_category=Town or City', max_digits=10),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='accommodation_others',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max per-night hotel cost for all other cluster categories', max_digits=10),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='accommodation_state_hq',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max per-night hotel cost when destination cluster_category=Metropolitan', max_digits=10),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='air_allowed',
            field=models.BooleanField(default=False, help_text='Is air travel allowed for this cadre?'),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='air_class',
            field=models.CharField(blank=True, help_text='e.g. Economy II A/c, On need basis, NA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='bus_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='bus_class',
            field=models.CharField(blank=True, help_text='e.g. A/c. Sleeper or Equivalent, A/c. Bus or Equivalent', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='car_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='car_notes',
            field=models.CharField(blank=True, help_text='e.g. At Management discretion / Company car, NA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='company_guest_house_status',
            field=models.CharField(choices=[('Preferred', 'Preferred (Strong Preference)'), ('Optional', 'Optional'), ('Exceptional Only', 'Exceptional Only (Hotel in rare cases)')], default='Optional', help_text='Company Guest House policy for this cadre', max_length=20),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='daily_allowance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat daily allowance amount for this cadre', max_digits=10),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='local_conveyance_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='local_conveyance_type',
            field=models.CharField(blank=True, help_text='e.g. Online Cab/3-Wheeler for Hire, 2 or 3 Wheeler, NA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='own_stay_districts_pct',
            field=models.DecimalField(decimal_places=2, default=50, help_text='% of Districts hotel limit for own stay', max_digits=5),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='own_stay_others_pct',
            field=models.DecimalField(decimal_places=2, default=50, help_text='% of Others hotel limit for own stay', max_digits=5),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='own_stay_state_hq_pct',
            field=models.DecimalField(decimal_places=2, default=50, help_text='% of State HQ hotel limit paid when employee stays at own accommodation', max_digits=5),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='train_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='train_class',
            field=models.CharField(blank=True, help_text='e.g. Sleeper or Equivalent, III A/c or Equivalent', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='cluster_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cadre',
            name='name',
            field=models.CharField(help_text='e.g. ADMINISTRATIVE, MANAGERIAL - PAN INDIA', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='eligibilityrule',
            name='cadre',
            field=models.OneToOneField(help_text='One rule set per cadre', on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rule', to='travel_masters.cadre'),
        ),
        migrations.RemoveField(
            model_name='eligibilityrule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='eligibilityrule',
            name='city_type',
        ),
        migrations.RemoveField(
            model_name='eligibilityrule',
            name='eligibility_class',
        ),
        migrations.RemoveField(
            model_name='eligibilityrule',
            name='limit_amount',
        ),
    ]
