# Generated by Django 5.1.1 on 2026-06-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_masters', '0002_entitlement_policy_cadre_eligibilityrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrule',
            name='districts_clusters',
            field=models.JSONField(blank=True, default=list, help_text="Cluster categories mapped to Districts (e.g. ['Town', 'City'])", null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='others_clusters',
            field=models.JSONField(blank=True, default=list, help_text="Cluster categories mapped to Others (e.g. ['Others'])", null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='state_hq_clusters',
            field=models.JSONField(blank=True, default=list, help_text="Cluster categories mapped to State HQ (e.g. ['Metropolitan'])", null=True),
        ),
        migrations.AlterField(
            model_name='eligibilityrule',
            name='accommodation_districts',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max per-night hotel cost for Districts accommodation tier', max_digits=10),
        ),
        migrations.AlterField(
            model_name='eligibilityrule',
            name='accommodation_others',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max per-night hotel cost for Others accommodation tier', max_digits=10),
        ),
        migrations.AlterField(
            model_name='eligibilityrule',
            name='accommodation_state_hq',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max per-night hotel cost for State HQ accommodation tier', max_digits=10),
        ),
    ]
