# Generated by Django 5.1.1 on 2026-06-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_masters', '0003_eligibilityrule_districts_clusters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this policy/entitlement rule active for this cadre?'),
        ),
    ]
