# Generated by Django 5.1.1 on 2026-06-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_masters', '0004_eligibilityrule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrule',
            name='travel_rules',
            field=models.JSONField(blank=True, default=dict, help_text="Dynamic travel rules mapping mode names to list of allowed classes. e.g. {'long_distance': [], 'local_conveyance': []}", null=True),
        ),
    ]
