# Generated by Django 5.1.1 on 2026-06-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_masters', '0005_eligibilityrule_travel_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrule',
            name='max_mileage_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum permitted odometer/distance limit per cadre in km', max_digits=10),
        ),
    ]
