# Generated by Django 5.1.1 on 2026-06-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_masters', '0006_eligibilityrule_max_mileage_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrule',
            name='laundry_days_threshold',
            field=models.IntegerField(default=4, help_text='Minimum stay nights in guest house for laundry to be applicable'),
        ),
    ]
