# Generated by Django 5.1.1 on 2026-07-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_masters', '0007_eligibilityrule_laundry_days_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrule',
            name='max_mileage_bike_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum permitted bike odometer/distance limit per cadre in km', max_digits=10),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='max_mileage_car_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum permitted car odometer/distance limit per cadre in km', max_digits=10),
        ),
    ]
