# Generated by Django 5.1.1 on 2026-07-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_masters', '0008_eligibilityrule_max_mileage_bike_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrule',
            name='monthly_tour_daily_allowance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat daily allowance amount for monthly tours for this cadre', max_digits=10),
        ),
    ]
