# Generated by Django 5.1.1 on 2026-07-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_masters', '0009_eligibilityrule_monthly_tour_daily_allowance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityrule',
            name='company_guest_house_status',
            field=models.CharField(choices=[('Preferred', 'Preferred (Strong Preference)'), ('Optional', 'Optional'), ('Exceptional Only', 'Exceptional Only (Hotel in rare cases)'), ('available', 'Available (Legacy - maps to Optional)')], default='Optional', help_text='Company Guest House policy for this cadre', max_length=20),
        ),
    ]
