# Generated by Django 5.2.9 on 2026-04-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(max_length=50)),
                ('minimum_supported_version', models.CharField(max_length=50)),
                ('update_type', models.CharField(choices=[('optional', 'Optional'), ('force', 'Force')], max_length=20)),
                ('message', models.TextField()),
                ('update_url', models.URLField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
