# Generated by Django 4.2.7 on 2026-04-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_reset_otp_user_reset_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carry_forward_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
