# Generated by Django 4.2.7 on 2026-05-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_position_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
