# Generated by Django 5.1.1 on 2026-06-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_active_position_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_position_id',
        ),
    ]
