# Generated by Django 5.1.1 on 2026-06-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_active_position_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('employee', 'Specific Employee'), ('position', 'Specific Position')], max_length=20)),
                ('target_id', models.CharField(max_length=100)),
                ('target_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Access Control',
                'verbose_name_plural': 'Report Access Controls',
                'unique_together': {('access_type', 'target_id')},
            },
        ),
    ]
