# Generated by Django 5.1.1 on 2026-06-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reportaccesscontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaccesscontrol',
            name='employee_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportaccesscontrol',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportaccesscontrol',
            name='position_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportaccesscontrol',
            name='position_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
