# Generated by Django 5.1.1 on 2026-07-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plain_password',
        ),
    ]
